### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by brandongit2** [brandongit2/recipes#1]
- [ ] Set up Snowpack (using it for the first time)
- [ ] Firebase auth
- [ ] Set up Firebase Realtime Database
  - I've used Firestore before, but I've decided to switch to Realtime Database.
- [ ] Ability to see/add recipes

And I'll improvise from here.
